### ISSUE TITLE
Asciinema link broken

### ISSUE THREAD

**Issue by kvolkovich-sc** [Angelmmiguel/svgi#10]
This link is broken. https://asciinema.org/a/123343
Please fix.

**Comment by Angelmmiguel** [comment]
Hello @kvolkovich-sc!

Thank you for the issue. It seems to be a temporary issue with the certificate:

![Certificate issue](https://user-images.githubusercontent.com/4056725/26872027-6d099e50-4b75-11e7-935d-baf0cbf2bfe5.png)

However, the problem is already resolved. Now, I can access to [Asciinema](https://asciinema.org/a/123343).
